; config_model.ini

; [data]
data_file = data/inputs/dataOhre_Brezova.csv  ; hourly/daily data for the run
id = Brezova
id_col = VD
columns = PREP, bal_inflow
timestamp = DTM  ; date (daily data), hour_start (hourly data); DTM (Ohre)

; [model]
trainer = online_bp ; online_bp, batch_bp, online_adam, batch_adam, online_bp_epoch, batch_bp_epoch, online_adam_epoch, batch_adam_epoch, online_bp_momentum, online_bp_penalize, online_bp_momentum_epoch, online_bp_penalize_epoch
architecture = 0
input_numbers = 0 | 0   ;  length must match number of columns
activation = RELU ; RELU, SIGMOID, LINEAR, TANH, GAUSSIAN, ... (choose type for each layer in "architecture" or one, same for all)
weight_init = XG  ; RANDOM, LHS, LHS2 , HE (for relu) , XG (for sigmoid, tanh)

lstm_time_steps = 10 ; history (input) time steps
lstm_cells = 10 ; output horizont

; [training]
ensemble_runs = 10
max_iterations = 500
max_metrics_step = 50  ; total number of metrics written into file = ceil(max_iterations % max_metrics_step)
max_error = 0.002
learning_rate = 0.001
shuffle = true
seed = 0  ; 0 = random
batch_size = 30  ; used only for batch trainer
train_fraction = 0.8
split_shuffle = false  ; false = chronological, true = random train/validation split
transform = MINMAX   ; NONE, MINMAX, NONLINEAR, ZSCORE  (choose type for each column in "columns" or one, same for all)
transform_alpha = 5.0  ; param
exclude_last_col_from_transform = false
remove_na_before_calib = true

; [optimization]
pso_optimize = false

; [paths] 
out_dir = data/outputs/
log_dir = data/outputs/logs/
calib_mat = data/outputs/calib_mat.csv
weights_csv_init = data/outputs/weights/weights_init.csv
weights_bin_init = data/outputs/weights/weights_init.bin
weights_vec_csv_init = data/outputs/weights/weights_init_vector.csv
weights_vec_bin_init = data/outputs/weights/weights_init_vector.bin
weights_csv = data/outputs/weights/weights_final.csv
weights_bin = data/outputs/weights/weights_final.bin
weights_vec_csv = data/outputs/weights/weights_final_vector.csv
weights_vec_bin = data/outputs/weights/weights_final_vector.bin
real_calib = data/outputs/calib_real.csv
pred_calib = data/outputs/calib_pred.csv
real_valid = data/outputs/valid_real.csv
pred_valid = data/outputs/valid_pred.csv
metrics_cal = data/outputs/metrics/calib_metrics.csv
metrics_val = data/outputs/metrics/valid_metrics.csv
run_info = data/outputs/metrics/run_info.csv
errors_csv = data/outputs/metrics/errors.csv
pattern_indices = data/outputs/pattern_indices.csv